<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
        <Folder Include="Queries\GetTaskById\"/>
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="FluentValidation" Version="12.0.0-preview1"/>
        <PackageReference Include="FluentValidation.AspNetCore" Version="11.3.0"/>
        <PackageReference Include="FluentValidation.DependencyInjectionExtensions" Version="11.11.0"/>
        <PackageReference Include="MediatR" Version="12.5.0"/>
        <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="9.0.12"/>
        <PackageReference Include="Scrutor" Version="6.0.1"/>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\Task.Domain\Task.Domain.csproj"/>
        <ProjectReference Include="..\Task.Infrastructure\Task.Infrastructure.csproj"/>
    </ItemGroup>

</Project>
